spring:
  application:
    name: thinh
  datasource:
    url: ${DB_URL_LOCAL}
    username: ${DB_URL_LOCAL}
    password: ${DB_URL_LOCAL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  groq:
    api-key: ${thinh.groq_api_key:}