spring:
  application:
    name: thinh
  profiles:
    active: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  docker:
    compose:
      enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

thinh:
  jwt:
    base64-secret: lgc9aOKjB6CneazJNnvLl2p1vwkO9T291yxz1Jk68CUNFmKqWnOIKvdkQggu6iusuaVlrasWrp3Vbo/ixE8fWA==
    access-token-validity-in-seconds: 8640000
    refresh-token-validity-in-seconds: 8640000
  upload-file:
    base-uri: "D:/Projects/sportify/data/"
  groq:
    api-key: ${thinh.groq_api_key:}
