spring.application.name=thinh
spring.datasource.url=jdbc:postgresql://localhost:5433/sportstore
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#JWT
thinh.jwt.base64-secret=lgc9aOKjB6CneazJNnvLl2p1vwkO9T291yxz1Jk68CUNFmKqWnOIKvdkQggu6iusuaVlrasWrp3Vbo/ixE8fWA==
#Expiration: 1 day (seconds)
thinh.jwt.access-token-validity-in-seconds=8640000
thinh.jwt.refresh-token-validity-in-seconds=8640000

thinh.upload-file.base-uri=D:/Projects/sportify/data/

# Groq AI Configuration
thinh.groq.api-key=${thinh.groq_api_key:}
